name: Publish Docker Image
on: [push]
jobs:
  push-to-github-package-registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Alpine version to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rkhozinov/docker-alpine-awscli/docker-alpine-awscli
        username: ${{ secrets.GITHUB_PACKAGE_REGISTRY_USERNAME }}
        password: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        tag_names: true
        cache: true

  push-to-dockerhub:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - name: Publish to Dockerhub
     uses: elgohr/Publish-Docker-Github-Action@master
     with:
       name: rkhozinov/alpine-awscli
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       dockerfile: Dockerfile
       tag_names: true
       cache: true
